"""
Constants for the chatbot RAG solution.
"""

# Database constants
DEFAULT_DB_PORT = 5432
DB_CONNECTION_TIMEOUT = 30
DB_QUERY_TIMEOUT = 90
DB_BATCH_SIZE = 10

# Token and text processing constants
MAX_TOKEN_LENGTH = 4000
MAX_MESSAGE_LENGTH = 2000
CHUNK_OVERLAP_SIZE = 200
DEFAULT_CHUNK_SIZE = 1000
MIN_CHUNK_SIZE = 100
MAX_CHUNK_SIZE = 8000

# Time constants (in seconds)
CACHE_TTL_SECONDS = 3600  # 1 hour
BEDROCK_CACHE_TTL_SECONDS = 259200  # 72 hours (3 days)
ROTATION_INTERVAL_DAYS = 90
LOG_RETENTION_DAYS = 7
BACKUP_RETENTION_DAYS = 7

# HTTP status codes
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_FORBIDDEN = 403
HTTP_INTERNAL_ERROR = 500

# Lambda memory and timeout settings
LAMBDA_MEMORY_SIZE = 256
LAMBDA_TIMEOUT_MINUTES = 5

# Textract and document processing
MAX_DOCUMENT_SIZE_MB = 10
TEXTRACT_MAX_PAGES = 100

# Vector database settings
VECTOR_SIMILARITY_THRESHOLD = 0.7
DEFAULT_VECTOR_LIMIT = 5
EMBEDDING_DIMENSIONS = 1536

# Rate limiting
DEFAULT_RATE_LIMIT_PER_MINUTE = 10
DEFAULT_RATE_LIMIT_PER_HOUR = 100

# Year constants for date validation
CURRENT_YEAR = 2023
MIN_VALID_YEAR = 1900
MAX_VALID_YEAR = 2100

# Retry and backoff settings
MAX_RETRY_ATTEMPTS = 3
INITIAL_BACKOFF_SECONDS = 1
MAX_BACKOFF_SECONDS = 60

# File size limits
MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB
MAX_BATCH_SIZE = 100

# WebSocket settings
WEBSOCKET_TIMEOUT_SECONDS = 30
HEARTBEAT_INTERVAL_SECONDS = 30

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
